### ISSUE TITLE
memory tracing problems

### ISSUE THREAD

**Issue by lyliu** [s0i37/DBI#1]
Hi,
I have some problems.
1. Is it necessary to trace memory?  I see that it stores the address into "memoryInput",which doesn't affect pin , memory or registers, What does the function of "restore_memory"do?
2. I have difficult in understanding how to set fuzz_data in function "FUZZ", does the data address exist in the REG_GCX register for all programs? and what do three "for" functions do?
Looking forward to your reply.

**Comment by s0i37** [comment]
Hello.
Modules `pin/afl/fuzz.cpp` and `pin/winafl/fuzz.cpp` were created just for my https://github.com/s0i37/afl_inmemory and https://github.com/s0i37/winafl_inmemory repositories by experimental reason.
You may read http://shell-storm.org/blog/In-Memory-fuzzing-with-Pin/ for explanation. I was inspired this article and tried to implement this with afl/winafl.
restore_memory() - makes rollback all changes with memory after iteration.
fuzz_data() - implements delivering fuzz data for target process (via pipe_data).
However, today I am not use it, because the tuning for fuzzing with this approach very difficult. You may see my another fork of afl/winafl with more simple changes for network services fuzzing.

**Comment by s0i37** [comment]
Now I use only `pin/afl/cover.cpp` and `pin/winafl/cover.cpp`.
You may see examples for using this instrumentation in https://github.com/s0i37/afl
